apiVersion: v1
kind: Service
metadata:
    name: thanos-frontend-service
spec:
    selector:
        app: thanos-frontend
    ports:
        - protocol: TCP
            port: 80
            targetPort: 80
    type: NodePort