apiVersion: v1
kind: Service
metadata:
  name: thanos-frontend
  namespace: monitoring-testing-october20
spec:
  type: LoadBalancer
  selector:
    app: thanos-frontend
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092