apiVersion: v1
kind: Service
metadata:
  name: thanos-read-write
  namespace: monitoring-testing-october20
spec:
  type: LoadBalancer
  selector:
    app: thanos-read-write
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090