apiVersion: v1
kind: Service
metadata:
  name: thanos-receiver
  namespace: monitoring-testing-october20
spec:
  type: LoadBalancer
  selector:
    app: thanos-receiver
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091