
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-query-frontend-pvc
  namespace: monitoring-testing-october24
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard