apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: receive
  namespace: monitoring-testing-october24
spec:
  rules:
  - host: receive.refactored-space-bassoon-6447q4747g5h56rq.github.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: receive
            port:
              number: 80
  tls:
  - hosts:
    - receive.refactored-space-bassoon-6447q4747g5h56rq.github.dev
    secretName: receive-tls