apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-values
  namespace: monitoring-testing-october24

# Default values for Thanos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  global: |
    imageRegistry: ""
    imagePullSecrets: []
    storageClass: ""

  nameOverride: ""
  fullnameOverride: ""

  serviceAccount:
    create: true
    name: ""

  rbac:
    create: true

  podSecurityPolicy:
    enabled: false

  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  service:
    type: ClusterIP
    port: 9090

  ingress:
    enabled: false
    annotations: {}
    hosts:
      - host: chart-example.local
        paths: []
    tls: []

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  service:
    query-frontend:
      port: 9090
    receiver:
      port: 10901
    readwrite:
      port: 9091

  frontend: |
    replicaCount: 1
    image:
      registry: docker.io
      repository: bitnami/thanos
      tag: 0.36.1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9090
    ingress:
      enabled: false
      annotations: {}
      hosts:
        - host: frontend.example.local
          paths: []
      tls: []
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  readwrite: |
    enabled: true
    args:
      - --web.external-prefix=/thanos-readwrite

  receiver: |
    replicaCount: 1
    image:
      registry: docker.io
      repository: bitnami/thanos
      tag: 0.36.1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 10901
    ingress:
      enabled: false
      annotations: {}
      hosts:
        - host: receiver.example.local
          paths: []
      tls: []
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  query-frontend: |
    replicaCount: 1
    image:
      registry: docker.io
      repository: bitnami/thanos
      tag: 0.36.1
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 9090
    ingress:
      enabled: false
      annotations: {}
      hosts:
        - host: query-frontend.example.local
          paths: []
      tls: []
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}